### ISSUE TITLE
Not working on android

### ISSUE THREAD

**Issue by ugrdursun** [gorhom/react-native-animated-tabbar#112] opened 2021-06-15 07:48 UTC
Animated tab bar not working on android. 

Animations are working but Tabs are not touchable. 

Its perfectly working on iOS but not android. How can i solve this ?

```
    "react-native-reanimated": "^1.10.0",
    "react-native-redash": "^16.0.11",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.10.3",
```

**Comment by darkbasic** [comment] 2021-06-28 16:05
Seriously? I was sure I had to be doing something wrong...
For me it also crashes if I try to enable Debugging, does it?

**Comment by darkbasic** [comment] 2021-06-28 16:14
I think this is a duplicate of https://github.com/gorhom/react-native-animated-tabbar/issues/103

**Comment by darkbasic** [comment] 2021-06-29 09:48
It's not a bug in the library, but a misconfiguration in react-native-gesture-handler: https://docs.swmansion.com/react-native-gesture-handler/docs/#updating-mainactivityjava

This should be closed.

**Closed** 2021-06-29 18:40 UTC
Labels: bug

**Comment by kelvinndmo** [comment] 2022-01-05 16:48
Issues is in this package are very disappointing, good work though @gorhom

**Comment by kelvinndmo** [comment] 2022-01-05 16:51
@darkbasic can you mind shedding more light on the misconfiguration, for me its working on IOS and not on Android

**Comment by darkbasic** [comment] 2022-01-09 15:59
@kelvinndmo newest version changed its installation instructions, follow the new ones and you'll be good.

**Comment by briantanabe** [comment] 2022-04-12 03:38
@darkbasic Can you please be more specific – it's unclear what you're referring to in the link in your comment from June 29, and I have no idea what installation instructions you're referring to on January 9 (I can't find any required changes in installation this library nor react-native-gesture-handler). It seems like the tab buttons not working is a common problem on Android, and there are a ton of frustrated issues opened to that effect.

**Comment by darkbasic** [comment] 2022-05-05 12:51
I simply mean that react-native-gesture-handler had some installation instructions which needed to be followed in order to have react-native-animated-tabbar working on Android. I can't be more specific because I don't remember what exactly did the trick, but what I had to do was to simply follow the react-native-gesture-handler installation instructions.

**Comment by briantanabe** [comment] 2022-05-05 12:57
I had to uninstall this package altogether because of this bug, and I've been using it for over a year. None of the installation instructions for react-native-gesture-handler worked for me... I'd love if we could re-open this issue, as I think it's related to #132
